In [1]:
from sklearn.preprocessing import FunctionTransformer
import numpy as np


In [4]:
def log_transform(x):
    return np.log1p(x)  # np.log1p(x) computes log(1 + x) to handle zeros.

# Create a FunctionTransformer for the log transformation
log_transformer=FunctionTransformer(log_transform)

# Example dataset
data=np.array([[1,10,100],[1000,5000,10000]])

# Apply the log transformation
log_transformed=log_transformer.fit_transform(data)

# Print the results
print('Original data:\n', data)
print("Log Transformed Data\n",log_transformed)



Original data:
 [[    1    10   100]
 [ 1000  5000 10000]]
Log Transformed Data
 [[0.69314718 2.39789527 4.61512052]
 [6.90875478 8.51739317 9.21044037]]
