<h1 style='color:#DE006F'>USING NUMPY</h1>

In [2]:
import numpy as np

#EXAMPLE DATA
data=np.array([[1,2,3],[4,5,6]])

# Reciprocal transformation
reciprocal_transformed=1/(data + 1e-9)

print('Orginal Data\n',data)
print('\nReciprocal Transformed Data:\n',reciprocal_transformed)

Orginal Data
 [[1 2 3]
 [4 5 6]]

Reciprocal Transformed Data:
 [[1.         0.5        0.33333333]
 [0.25       0.2        0.16666667]]


<h1 style='color:#DE006F'>Using Scikit-learn's FunctionTransformer</h1>

In [3]:
from sklearn.preprocessing import FunctionTransformer
import numpy as np

In [7]:
def reciprocal_transform(x):
    return 1 / (x + 1e-9)   # Add a small constant to avoid division by zero

reciprocal_transformer=FunctionTransformer(reciprocal_transform)

data=np.array([[1,2,3],[4,5,6]])

reciprocal_transformed=reciprocal_transformer.fit_transform(data)

print('Orginal Data: \n',data)
print('\nReciprocal Transformed Data: \n', reciprocal_transformed)

Orginal Data: 
 [[1 2 3]
 [4 5 6]]

Reciprocal Transformed Data: 
 [[1.         0.5        0.33333333]
 [0.25       0.2        0.16666667]]
